#!/bin/bash
cp gg-linux-x86_64 /usr/local/bin/gg
chmod u+x /usr/local/bin/gg
gg config -w node=vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIummmea4r0dDUCIsDQogICJhZGQiOiAiMzUuMjIwLjIwMS4xMDIiLA0KICAicG9ydCI6ICI4ODg4IiwNCiAgImlkIjogIjBlY2JiODYyLThkODItNDZhYi1hMDI0LTNmMzhlZTc3Mzk3ZCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAibm9uZSIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiIiwNCiAgInRscyI6ICJub25lIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9
