#!/bin/bash
cp gg-linux-x86_64 /usr/local/bin/gg
chmod u+x /usr/local/bin/gg
gg config -w node=vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIjEiLA0KICAiYWRkIjogIjE3OC4xNTcuNTguODAiLA0KICAicG9ydCI6ICI4ODg4IiwNCiAgImlkIjogIjBlY2JiODYyLThkODItNDZhYi1hMDI0LTNmMzhlZTc3Mzk3ZCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYWVzLTEyOC1nY20iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAibm9uZSIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIg0KfQ==
